# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "/phoneme-informed-transcription-blog"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Sangeon Yong
  url:        https://seyong92.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
